<?php

/**
 * @file
 * Message in Fabecook style.
 */

/**
 * Implements hook_theme().
 */
function message_fb_theme(){
  return array(
    'message_fb' =>  array(
      'template' => 'theme/message-fb',
      'render element' => 'entity'
    ),
  );
}

function message_fb_preprocess_entity(&$variables) {
  if ($variables['entity_type'] != 'message') {
    return;
  }

  // Check if we have a Babble field on the Message entity.
  $message = $variables['message'];
  $babble_field = FALSE;
  foreach (field_info_instances('message', $message->type) as $field_name => $instance) {
    $field = field_info_field($field_name);
    if ($field['type'] == 'babble') {
      $babble_field = $field_name;
      break;
    }
  }

  if (!$babble_field) {
    // Not a Babble field.
    return;
  }

  $variables['babble_field'] = $babble_field;
  $variables['theme_hook_suggestions'][] = 'message_fb';

  $babble_body_field = &$variables['content'][$babble_field . '_babble_comment_form']['babble_body'][LANGUAGE_NONE][0];

  $babble_body_field['#title_display'] = 'invisible';

  // Add HTML5 required.
  $babble_body_field['value']['#attributes']['required'] = 'required';

  $variables['content'][$babble_field . '_babble_comment_form']['#prefix'] = '';
  $variables['content'][$babble_field . '_babble_comment_form']['author']['_name']['#access'] = FALSE;

  // Get the user's picture.
  $account = user_load($variables['message']->uid);
  $picture = theme('user_picture', array('account' => $account));
  $variables['content']['picture'] = $picture ? $picture : '';

  // Add CSS.
  drupal_add_css(drupal_get_path('module', 'message_fb') . '/css/message_fb.css');
}
